version: "3"
services:
  api:
    build: python
    volumes:
      - ./log/gunicorn:/app/log/gunicorn
      - ./image:/app/image
      - ./font:/app/font
    privileged: true
    environment:
      TZ: Asia/Tokyo
    restart: always
  nextjs:
    build: next
    restart: always
  nginx:
    build: nginx
    volumes:
      - ./log/nginx:/var/log/nginx
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
    restart: always
